/*
 * This source file was generated by the Gradle 'init' task
 */
package spring.learn;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        RestServiceApplication classUnderTest = new RestServiceApplication();
    }
}
